resources:
  - name: step001
    type: newgitR/test2
    syntaxVersion: latest
    configuration:      
      test: foo

pipelines:
  - name: extensionstest
    steps:
      - name: step100
        type: gitcheck/test_test
        syntaxVersion: latest
        configuration:              
          foo: bar
          inputResources:
            - name: step001
        
