resources:
 - name: resource_1
   type: jfrog/SampleResource
   syntaxVersion: 0.0.3
   configuration:
     foo: Hello

pipelines:
 - name: sleep_pipeline_extension
   steps:
      - name: S_Bash_0023
        type: jfrog/HealthCheck
        syntaxVersion: 0.0.3
        configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           stuff:
              - "hi"
              - "hello"
