resources:
  - name: step001
    type: Gitnp/gittest1
    syntaxVersion: latest
    configuration:      
      test: foo

pipelines:
  - name: extensionstest
    steps:
      - name: step100
        type: gitcheck/gitstep
        syntaxVersion: latest
        configuration:              
          foo: bar
          inputResources:
            - name: step001
        
